### Read data from income.csv and scale the relevant features using standardization

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('/content/income.csv')

In [3]:
df

        Name  Age  Income  Buy
0        Rob   27   70000  Yes
1    Michael   29   90000   No
2      Mohan   29   61000  Yes
3     Ismail   28   60000  Yes
4       Kory   42  150000   No
5     Gautam   39  155000  Yes
6      David   41  160000  Yes
7     Andrea   38  162000   No
8       Brad   36  156000  Yes
9   Angelina   35  130000   No
10    Donald   37  137000   No
11       Tom   26   45000   No
12    Arnold   27   48000  Yes
13     Jared   28   51000   No
14     Stark   29   49500   No
15    Ranbir   32   53000   No
16    Dipika   40   65000  Yes
17  Priyanka   41   63000   No
18      Nick   43   64000  Yes
19      Alia   39   80000   No
20       Sid   41   82000  Yes
21     Abdul   39   58000   No

In [4]:
x = df[['Age', 'Income']]

In [5]:
st = StandardScaler()

y = st.fit_transform(x)
y

array([[-1.35605536, -0.48068427],
       [-1.00915747, -0.01015907],
       [-1.00915747, -0.69242061],
       [-1.18260641, -0.71594687],
       [ 1.24567876,  1.40141653],
       [ 0.72533193,  1.51904783],
       [ 1.07222982,  1.63667914],
       [ 0.55188299,  1.68373166],
       [ 0.20498511,  1.54257409],
       [ 0.03153617,  0.93089133],
       [ 0.37843405,  1.09557515],
       [-1.5295043 , -1.06884077],
       [-1.35605536, -0.99826199],
       [-1.18260641, -0.92768321],
       [-1.00915747, -0.9629726 ],
       [-0.48881065, -0.88063069],
       [ 0.89878087, -0.59831557],
       [ 1.07222982, -0.64536809],
       [ 1.4191277 , -0.62184183],
       [ 0.72533193, -0.24542167],
       [ 1.07222982, -0.19836915],
       [ 0.72533193, -0.76299939]])